from snakemake.io import touch, expand, directory
import pandas as pd


include: "rules/common.smk"


configfile: "config/config.yaml"


# List of final inputs to collect
final_inputs = []


if config.get("run_assembly", True):

    include: "rules/assembly.smk"

    final_inputs.extend(final_files("assembly"))


if config.get("run_annotation", False):

    include: "rules/annotation.smk"

    final_inputs.extend(final_files("annotation"))


if config.get("run_mutants", False):

    include: "rules/mutants.smk"

    final_inputs.extend(final_files("mutants"))


if config.get("run_phylogeny", False):

    include: "rules/phylogeny.smk"

    final_inputs.extend(final_files("phylogeny"))


rule all:
    input:
        final_inputs,
