import pandas as pd
from snakemake.io import touch, expand, directory
from scripts.python.utils import final_files, get_strains, get_parents

# main config file
configfile: "config/config.yaml"


# contains config validation function
include: "rules/common.smk"


# List of final inputs to collect
final_inputs = []


if config.get("run_assembly", True):

    include: "rules/assembly.smk"

    final_inputs.extend(final_files(config, "assembly"))


if config.get("run_annotation", False):

    include: "rules/annotation.smk"

    final_inputs.extend(final_files(config, "annotation"))


if config.get("run_mutants", False):

    include: "rules/mutants.smk"

    final_inputs.extend(final_files(config, "mutants"))


if config.get("run_phylogeny", False):

    include: "rules/phylogeny.smk"

    final_inputs.extend(final_files(config, "phylogeny"))


rule all:
    input:
        final_inputs,
