---
title: "Modelling"
author: "by A.G."
date: "last update: `r format(Sys.Date(), format = '%d %B %Y')`"
output:
  html_document:
    toc: yes
    df_print: paged
    code_folding: hide
    fig_width: 10
    fig_height: 6
    theme: cerulean
    highlight: kate
    toc_float: yes
  html_notebook:
    df_print: paged
    toc: yes
    number_sections: yes
    toc_float: yes
    theme: cerulean
    highlight: kate
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=10, fig.height=5, message = F, warning = F)
library(dplyr)
library(caret)
library(car)
library(ggplot2)
library(GGally)
```

## Read data set

Data set `features_amp_strain` has been made previously in `feature_engineering.Rmd`

```{r}
feat_amp <- as_tibble(read.csv("/home/andrei/Data/HeteroR/results/tables/features_amp.csv"))
feat_amp <- rename(feat_amp, n.plasmids="n_plasmids") %>% relocate(n.plasmids, .before="n.rep.total")
feat_amp$resistance_dummy <- ifelse(feat_amp$resistance=="R", 1, 0)
feat_amp
```

Selected variables (based on plots in feature_engineering)

```{r}
feat_selected <- feat_amp %>% select(c(strain, resistance, n.beta.lac, n.plasmids, med.rep.len, med.tot.rep.len, max.rep.len, n.rep.total, med.AR.len.cen))

feat_selected
```


```{r, fig.width=10, fig.height=10}
ggpairs(feat_selected, 
        columns=c(3:9), 
        aes(color=resistance, alpha=0.2, dotsize=0.02), 
        upper = list(continuous = wrap("cor", size = 2.5)),
        diag=list(continuous ="barDiag"))+
  scale_color_brewer(palette = "Set1")+
  scale_fill_brewer(palette = "Set1")
```

# Model 1

Let's try to build a simple model and then run its diagnostics

```{r}
fit1 <- lm(formula = resistance_dummy ~ n.beta.lac+n.plasmids+med.rep.len+med.tot.rep.len+max.rep.len+n.rep.total+med.AR.len.cen, data=feat_amp, family = "binomial")

summary(fit1)

```

```{r}
confint(fit1)
```

# Diagnostics

```{r,  fig.width=6, fig.height=4}
qqPlot(fit1, labels=feat_amp$strain, id.method="identify", simulate=T, main="Q-Q plot")
```

```{r}
durbinWatsonTest(fit1)
```

```{r}
crPlots(fit1)
```

```{r}
ncvTest(fit1)
```


------------------------------------------------------------------------

# Save the workspace

```{r, eval=FALSE}
save.image(f="/home/andrei/Data/HeteroR/notebooks/modelling.RData")
```
