---
title: "models_table"
output: html_document
date: "2023-06-27"
---

```{r}
library(readr)
library(tidymodels)
library(themis)
library(probably)
library(vip)
library(skimr)
library(stacks)
library(bestNormalize) # for ord QQ norm
library(tidyposterior) # for Bayesian ANOVA
#library(embed) # for UMAP
library(finetune) # for win-loss tuning
source("functions.R")

# path for models
models_path <- "/mnt/data/andrei/Data/HeteroR/results/models/scheme12/"
```
FROM modeling


# Read and process data

The data sets are the same as in EDA

```{r}
data_strain <- read_csv("data/features_strain.csv", na = c("NA", "-Inf")) %>% 
  filter(strain != "DA63310")

# TWO SCHEMES
hr_testing12 <- read_csv("data/heteroresistance_testing.csv", col_select = c(strain, Gr12)) %>% 
  filter(!is.na(strain)) %>% 
  rename("resistance" = Gr12 )

hr_testing13 <- read_csv("data/heteroresistance_testing.csv", col_select = c(strain, Gr13)) %>% 
  filter(!is.na(strain)) %>% 
  rename("resistance" = Gr13 )

# created during EDA
hr_testing <- read_csv("data/heteroresistance_testing_gr123.csv") 

# USE HR 1+2
data_strain <- data_strain %>% 
  left_join(hr_testing12, by = "strain")

data_strain %>% 
  group_by(resistance) %>% 
  count()
```

Add n.beta.lac \>4

```{r}
strains <- data_strain$strain

data_strain <- data_strain %>% 
  #mutate(n.beta.lac.3 = factor(ifelse(n.beta.lac > 3, "yes", "no"))) %>% 
  mutate(n.beta.lac.4 = factor(ifelse(n.beta.lac > 4, "yes", "no"))) %>% 
  relocate(n.beta.lac.4, .before = "n.plasmids") %>% 
  filter(resistance != "R") %>% 
  mutate(resistance = factor(resistance, levels = c("HR", "nonHR")),
         chrom.status = factor(chrom.status))

data_strain$N50 <- NULL
#data_strain$NA. <- NULL
data_strain[is.na(data_strain)] <- 0
```

# Data split

Stratified split

```{r}
set.seed(124)

data_split <- initial_split(data_strain, prop = 0.8, strata = resistance)

df_train <- training(data_split)
df_test <- testing(data_split)

cv_folds <- vfold_cv(df_train, strata = "resistance", v = 10, repeats = 10) 
```


#LR 

## LR MAIN 
```{r}
lr_main <- readRDS(paste0(models_path, "lr_main_space_p30.rds"))
mean_auc <-
  lr_main %>%   show_best("roc_auc", n = 1)  %>% select(mean) %>% as.character()
st_error <-
  lr_main %>%   show_best("roc_auc", n = 1) %>% select(std_err) %>% as.character()

mean_j_index <-
  lr_main %>%   show_best("j_index") %>% filter(.config == (
    lr_main %>% show_best("roc_auc", n = 1) %>% select(.config) %>%  as.character()
  )) %>%  select(mean) %>% as.character()


my_rec <- recipe(resistance ~ ., data = df_train) %>%
  update_role(strain, new_role = "ID") %>%
  step_nzv(all_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_smote(resistance, over_ratio = 1, seed = 100)

 my_mod <- logistic_reg(
        penalty = tune(),
        mixture = 1) %>%
      set_engine("glmnet")

 my_wf <- workflow() %>%
  add_model(my_mod) %>%
  add_recipe(my_rec)
 
best_params <- lr_main %>% 
    select_best("roc_auc")
 

final_model <- finalize_workflow(my_wf, best_params) %>%
  last_fit(data_split)

trained_mod <- final_model %>% 
  extract_workflow() %>% 
  pull_workflow_fit()

coefs <- coef(trained_mod$fit, s = lr_main %>%   show_best("roc_auc", n = 1) %>%  select(penalty) %>% as.numeric())

# -1 to remove intercept 
n_predictors <- coefs@i %>% length -1 

final_tibble <- tibble(Model = "LR", Preprocessin= "MAIN", mean_AUC = mean_auc, mean_j_index = mean_j_index, Correlation = NA, n_predictors =  n_predictors)

final_tibble
```

## LR NCORR 
```{r}
lr_ncorr_res <- readRDS(paste0(models_path, "lr_ncorr_p20.rds"))
mean_auc <-
  lr_ncorr_res %>%   show_best("roc_auc", n = 1)  %>% select(mean) %>% as.character()
st_error <-
  lr_ncorr_res %>%   show_best("roc_auc", n = 1) %>% select(std_err) %>% as.character()

mean_j_index <-
  lr_ncorr_res %>%   show_best("j_index") %>% filter(.config == (
    lr_ncorr_res %>% show_best("roc_auc", n = 1) %>% select(.config) %>%  as.character()
  )) %>%  select(mean) %>% as.character()

corr_tune <- lr_ncorr_res %>%   show_best("roc_auc", n = 1)  %>% select(corr_tune) %>% as.character()

#Rebuild the workflow to extract the number of selected features 
my_rec <- recipe(resistance ~ ., data = df_train) %>%
  update_role(strain, new_role = "ID") %>%
  step_nzv(all_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  #step_corr(threshold = opt$corr_threshold) %>%
  step_corr(all_predictors(), threshold = corr_tune) %>%
  step_smote(resistance, over_ratio = 1, seed = 100)

 my_mod <- logistic_reg(
        penalty = tune(),
        mixture = 1) %>%
      set_engine("glmnet")

 my_wf <- workflow() %>%
  add_model(my_mod) %>%
  add_recipe(my_rec)
 
best_params <- lr_ncorr_res %>% 
    select_best("roc_auc")
 

final_model <- finalize_workflow(my_wf, best_params) %>%
  last_fit(data_split)

trained_mod <- final_model %>% 
  extract_workflow() %>% 
  pull_workflow_fit()

coefs <- coef(trained_mod$fit, s = lr_ncorr_res %>%   show_best("roc_auc", n = 1) %>%  select(penalty) %>% as.numeric())

# -1 to remove intercept 
n_predictors <- coefs@i %>% length -1 

tmp_tibble <- tibble(Model = "LR", Preprocessin= "NCORR", mean_AUC = mean_auc, mean_j_index = mean_j_index, Correlation = corr_tune, n_predictors =  n_predictors)

final_tibble <- bind_rows(final_tibble,tmp_tibble)

final_tibble
```

## LR NCORQ

```{r}
lr_ncorq_res <- readRDS(paste0(models_path, "lr_ncorq_p30.rds"))
mean_auc <-
  lr_ncorq_res %>%   show_best("roc_auc", n = 1)  %>% select(mean) %>% as.character()
st_error <-
  lr_ncorq_res %>%   show_best("roc_auc", n = 1) %>% select(std_err) %>% as.character()

mean_j_index <-
  lr_ncorq_res %>%   show_best("j_index") %>% filter(.config == (
    lr_ncorq_res %>% show_best("roc_auc", n = 1) %>% select(.config) %>%  as.character()
  )) %>%  select(mean) %>% as.character()

corr_tune <- lr_ncorq_res %>%   show_best("roc_auc", n = 1)  %>% select(corr_tune) %>% as.character()

#Rebuild the workflow to extract the number of selected features 
my_rec <-recipe(resistance ~ ., data = df_train) %>%
  update_role(strain, new_role = "ID") %>%
  step_nzv(all_predictors()) %>%
  step_orderNorm(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_corr(all_predictors(), threshold = corr_tune) %>%
  step_smote(resistance, over_ratio = 1, seed = 100)

 my_mod <- logistic_reg(
        penalty = tune(),
        mixture = 1) %>%
      set_engine("glmnet")

 my_wf <- workflow() %>%
  add_model(my_mod) %>%
  add_recipe(my_rec)
 
best_params <- lr_ncorq_res %>% 
    select_best("roc_auc")
 

final_model <- finalize_workflow(my_wf, best_params) %>%
  last_fit(data_split)

trained_mod <- final_model %>% 
  extract_workflow() %>% 
  pull_workflow_fit()

coefs <- coef(trained_mod$fit, s = lr_ncorq_res %>%   show_best("roc_auc", n = 1) %>%  select(penalty) %>% as.numeric())

# -1 to remove intercept 
n_predictors <- coefs@i %>% length -1 

tmp_tibble <- tibble(Model = "LR", Preprocessin= "NCORQ", mean_AUC = mean_auc, mean_j_index = mean_j_index, Correlation = corr_tune, n_predictors =  n_predictors)

final_tibble <- bind_rows(final_tibble,tmp_tibble)

final_tibble
```


## LR PCA + YJ recipe
```{r}
lr_pcayj_res <- readRDS(paste0(models_path, "lr_pcayj_p20.rds"))
mean_auc <-
  lr_pcayj_res %>%   show_best("roc_auc", n = 1)  %>% select(mean) %>% as.character()
st_error <-
  lr_pcayj_res %>%   show_best("roc_auc", n = 1) %>% select(std_err) %>% as.character()

mean_j_index <-
  lr_pcayj_res %>%   show_best("j_index",n =20) %>% filter(.config == (
    lr_pcayj_res %>% show_best("roc_auc", n = 1) %>% select(.config) %>%  as.character()
  )) %>%  select(mean) %>% as.character()

corr_tune <- NA

#Rebuild the workflow to extract the number of selected features 
my_rec <- recipe(resistance ~ ., data = df_train) %>%
  update_role(strain, new_role = "ID") %>%
  step_nzv(all_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_smote(resistance, over_ratio = 1, seed = 100) %>%
  step_pca(all_predictors(), num_comp = tune()) %>%
  step_normalize(all_numeric_predictors())

 my_mod <- logistic_reg(
        penalty = tune(),
        mixture = 1) %>%
      set_engine("glmnet")

 my_wf <- workflow() %>%
  add_model(my_mod) %>%
  add_recipe(my_rec)
 
best_params <- lr_pcayj_res %>% 
    select_best("roc_auc")
 

final_model <- finalize_workflow(my_wf, best_params) %>%
  last_fit(data_split)

trained_mod <- final_model %>% 
  extract_workflow() %>% 
  pull_workflow_fit()

coefs <- coef(trained_mod$fit, s = lr_pcayj_res %>%   show_best("roc_auc", n = 1) %>%  select(penalty) %>% as.numeric())

# -1 to remove intercept 
n_predictors <- coefs@i %>% length -1 

tmp_tibble <- tibble(Model = "LR", Preprocessin= "PCA_YJ", mean_AUC = mean_auc, mean_j_index = mean_j_index, Correlation = corr_tune, n_predictors =  n_predictors)

final_tibble <- bind_rows(final_tibble,tmp_tibble)

final_tibble
```


##  LR NCORR + YJ 
... 
##  LR Ridge NCORR + YJ 

```{r, eval =FALSE}
lr0_ncoryj_res <- readRDS(paste0(models_path, "lr0_ncoryj_p20.rds"))
mean_auc <-
  lr0_ncoryj_res %>%   show_best("roc_auc", n = 1)  %>% select(mean) %>% as.character()
st_error <-
  lr0_ncoryj_res %>%   show_best("roc_auc", n = 1) %>% select(std_err) %>% as.character()

mean_j_index <-
  lr0_ncoryj_res %>%   show_best("j_index",n =20) %>% filter(.config == (
    lr0_ncoryj_res %>% show_best("roc_auc", n = 1) %>% select(.config) %>%  as.character()
  )) %>%  select(mean) %>% as.character()

corr_tune <- lr0_ncoryj_res %>%   show_best("roc_auc", n = 1)  %>% select(corr_tune) %>% as.character()

# given that ridge pushes thowards zero but not totally to zero I don't need to redo all the model but just preprocessing

n_predictors <- recipe(resistance ~ ., data = df_train) %>%
  update_role(strain, new_role = "ID") %>%
  step_nzv(all_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_YeoJohnson(all_numeric_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_smote(resistance, over_ratio = 1, seed = 100) %>%
  step_corr(all_predictors(), threshold = corr_tune) %>% prep() %>% juice() %>% colnames() %>% length()

tmp_tibble <- tibble(Model = "LR", Preprocessin= "Ridge_NCORR_YJ ", mean_AUC = mean_auc, mean_j_index = mean_j_index, Correlation = corr_tune, n_predictors =  n_predictors)

final_tibble <- bind_rows(final_tibble,tmp_tibble)

final_tibble

```

