---
title: "Poorly assembled strains"
format: html
editor: visual
---

```{r}
library(tidyverse)

data_strain <- read_csv("data/features_strain.csv", na = c("NA", "-Inf")) %>% 
  mutate(n.beta.lac.4 = factor(ifelse(n.beta.lac > 4, "yes", "no"))) %>% 
  relocate(n.beta.lac.4, .before = "n.plasmids") %>% 
  filter(strain != "DA63310") %>% 
  mutate(chrom.status = factor(chrom.status)) %>% 
  select(-contains("oriC")) %>% 
  select(-contains("plus"))

hr_testing <- read_csv("data/heteroresistance_testing.csv") %>% 
  filter(!is.na(strain), resistance != "R")

data_strain <- data_strain %>% 
  left_join(hr_testing, by = "strain") %>% 
  mutate(resistance = factor(resistance, levels = c("HR", "nonHR"))) %>% 
  filter(!is.na(resistance))
```

```{r}
data_strain %>% 
  ggplot(aes(coverage)) +
  geom_histogram(bins=50)
```

```{r}
data_strain %>% 
  select(contains("plasm"))
```

```{r, fig.width=6, fig.height=8}
library(ggpubr)

to_plot <- c("n.c.plasmids", "n.plasmids", "n.beta.lac.plasmid", "nc.beta.lac.plasmid", "n.rep.plasmid", "read.max.len")

get_splot <- function(col_name){
  data_strain %>% 
  ggplot(aes(coverage, .data[[col_name]])) +
  geom_point(aes(color = chrom.status)) +
    xlab("")
}

plot_list <- map(to_plot, ~ get_splot(.))

ggarrange(plotlist = plot_list, nrow = 3, ncol = 2, common.legend = T)
```

```{r}
data_strain %>% 
  filter(n.c.plasmids > 100 | n.rep.plasmid > 200) %>% 
  select(strain, coverage, chrom.status, n.rep.plasmid, n.c.plasmids) %>% 
  arrange(-n.c.plasmids)
```

```{r}
data_strain %>% 
  arrange(coverage )
```

```{r, fig.width=6, fig.height=8}
get_splot2 <- function(col_name){
  data_strain %>% 
  ggplot(aes(read.max.len, .data[[col_name]])) +
  geom_point(aes(color = coverage)) +
    xlab("")
}

plot_list2 <- map(to_plot, ~ get_splot2(.))

ggarrange(plotlist = plot_list2, nrow = 3, ncol = 2, common.legend = T)
```
