# strain names
strains: "configs/strains_mutants.csv"

# raw reads (mutants) path
raw_path: "resources/raw/mutants"
 
# qual and BGI-adapters trimming
trim_front: 10
adapter1: AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA
adapter2: AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG

# var.calling
max_depth: 800
ploidy: 1
prior: "5.0e-10"

# var.filtering
indel_dist: 3
quality: 30
depth: 20

# over-covered regions, a.k.a. amplifications
z_threshold: 3
window_size: 1000

# raltive coverage
min_contig_len: 1000
